/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jni.hello.world;

public class App {
    public native void sayHelloWorld();

    static{
        System.loadLibrary("HelloWorldImpl");
        //System.load(System.getProperty("user.dir") + "/libHelloWorldImpl.jnilib");
    }

    public static void main(String[] args){
        final App helloWorld = new App();
        helloWorld.sayHelloWorld();
    }
}
