/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jni.hello.world;

public class App {
    public native void helloWorld();

    static{
        System.loadLibrary("HelloWorldImpl");
        //System.load(System.getProperty("user.dir") + "/libHelloWorldImpl.jnilib");
    }

    public static void main(String[] args){
        System.out.println(System.getProperty("java.library.path"));
        final App helloWorld = new App();
        helloWorld.helloWorld();
    }
}
